// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum LegacyStorePigeonPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// 確認画面が表示する入力内容。
///
/// 項目ごとにメソッドを分けず**まとめて返す**（手順6.1節）。項目が増えるたびに
/// ネイティブ側の変更が必要になるのを避けるため。
///
/// Generated class from Pigeon that represents data sent in messages.
struct FormDataDto: Hashable, CustomStringConvertible {
  var name: String
  var email: String
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FormDataDto? {
    let name = pigeonVar_list[0] as! String
    let email = pigeonVar_list[1] as! String
    let message = pigeonVar_list[2] as! String

    return FormDataDto(
      name: name,
      email: email,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      email,
      message,
    ]
  }
  static func == (lhs: FormDataDto, rhs: FormDataDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return LegacyStorePigeonPigeonInternal.deepEquals(lhs.name, rhs.name) && LegacyStorePigeonPigeonInternal.deepEquals(lhs.email, rhs.email) && LegacyStorePigeonPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("FormDataDto")
    LegacyStorePigeonPigeonInternal.deepHash(value: name, hasher: &hasher)
    LegacyStorePigeonPigeonInternal.deepHash(value: email, hasher: &hasher)
    LegacyStorePigeonPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "FormDataDto(name: \(String(describing: name)), email: \(String(describing: email)), message: \(String(describing: message)))"
  }
}

private class LegacyStorePigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return FormDataDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LegacyStorePigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FormDataDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LegacyStorePigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LegacyStorePigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LegacyStorePigeonPigeonCodecWriter(data: data)
  }
}

class LegacyStorePigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = LegacyStorePigeonPigeonCodec(readerWriter: LegacyStorePigeonPigeonCodecReaderWriter())
}

/// 移行前のネイティブコードが保持しているデータを読む。
///
/// このデータの所有者はネイティブのままで、Flutterからは読むだけ
/// （手順6.2節）。移行が完了した時点でこのAPIごと消える。
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LegacyStoreApi {
  func readFormData() throws -> FormDataDto
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LegacyStoreApiSetup {
  static var codec: FlutterStandardMessageCodec { LegacyStorePigeonPigeonCodec.shared }
  /// Sets up an instance of `LegacyStoreApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LegacyStoreApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let readFormDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.legacyapp_flutter.LegacyStoreApi.readFormData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readFormDataChannel.setMessageHandler { _, reply in
        do {
          let result = try api.readFormData()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      readFormDataChannel.setMessageHandler(nil)
    }
  }
}
