// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.example.legacyapp.flutter;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class LegacyStorePigeon {

  static boolean pigeonDoubleEquals(double a, double b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0 ? 0.0 : a) == (b == 0.0 ? 0.0 : b) || (Double.isNaN(a) && Double.isNaN(b));
  }

  static boolean pigeonFloatEquals(float a, float b) {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (a == 0.0f ? 0.0f : a) == (b == 0.0f ? 0.0f : b) || (Float.isNaN(a) && Float.isNaN(b));
  }

  static int pigeonDoubleHashCode(double d) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (d == 0.0) {
      d = 0.0;
    }
    long bits = Double.doubleToLongBits(d);
    return (int) (bits ^ (bits >>> 32));
  }

  static int pigeonFloatHashCode(float f) {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    if (f == 0.0f) {
      f = 0.0f;
    }
    return Float.floatToIntBits(f);
  }

  static boolean pigeonDeepEquals(Object a, Object b) {
    if (a == b) { return true; }
    if (a == null || b == null) { return false; }
    if (a instanceof byte[] && b instanceof byte[]) {
      return Arrays.equals((byte[]) a, (byte[]) b);
    }
    if (a instanceof int[] && b instanceof int[]) {
      return Arrays.equals((int[]) a, (int[]) b);
    }
    if (a instanceof long[] && b instanceof long[]) {
      return Arrays.equals((long[]) a, (long[]) b);
    }
    if (a instanceof double[] && b instanceof double[]) {
      double[] da = (double[]) a;
      double[] db = (double[]) b;
      if (da.length != db.length) {
        return false;
      }
      for (int i = 0; i < da.length; i++) {
        if (!pigeonDoubleEquals(da[i], db[i])) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof List && b instanceof List) {
      List<?> listA = (List<?>) a;
      List<?> listB = (List<?>) b;
      if (listA.size() != listB.size()) { return false; }
      for (int i = 0; i < listA.size(); i++) {
        if (!pigeonDeepEquals(listA.get(i), listB.get(i))) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Map && b instanceof Map) {
      Map<?, ?> mapA = (Map<?, ?>) a;
      Map<?, ?> mapB = (Map<?, ?>) b;
      if (mapA.size() != mapB.size()) { return false; }
      for (Map.Entry<?, ?> entryA : mapA.entrySet()) {
        Object keyA = entryA.getKey();
        Object valueA = entryA.getValue();
        boolean found = false;
        for (Map.Entry<?, ?> entryB : mapB.entrySet()) {
          Object keyB = entryB.getKey();
          if (pigeonDeepEquals(keyA, keyB)) {
            Object valueB = entryB.getValue();
            if (pigeonDeepEquals(valueA, valueB)) {
              found = true;
              break;
            } else {
              return false;
            }
          }
        }
        if (!found) {
          return false;
        }
      }
      return true;
    }
    if (a instanceof Double && b instanceof Double) {
      return pigeonDoubleEquals((double) a, (double) b);
    }
    if (a instanceof Float && b instanceof Float) {
      return pigeonFloatEquals((float) a, (float) b);
    }
    return a.equals(b);
  }

  static int pigeonDeepHashCode(Object value) {
    if (value == null) { return 0; }
    if (value instanceof byte[]) {
      return Arrays.hashCode((byte[]) value);
    }
    if (value instanceof int[]) {
      return Arrays.hashCode((int[]) value);
    }
    if (value instanceof long[]) {
      return Arrays.hashCode((long[]) value);
    }
    if (value instanceof double[]) {
      double[] da = (double[]) value;
      int result = 1;
      for (double d : da) {
        result = 31 * result + pigeonDoubleHashCode(d);
      }
      return result;
    }
    if (value instanceof List) {
      int result = 1;
      for (Object item : (List<?>) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Map) {
      int result = 0;
      for (Map.Entry<?, ?> entry : ((Map<?, ?>) value).entrySet()) {
        result += ((pigeonDeepHashCode(entry.getKey()) * 31) ^ pigeonDeepHashCode(entry.getValue()));
      }
      return result;
    }
    if (value instanceof Object[]) {
      int result = 1;
      for (Object item : (Object[]) value) {
        result = 31 * result + pigeonDeepHashCode(item);
      }
      return result;
    }
    if (value instanceof Double) {
      return pigeonDoubleHashCode((double) value);
    }
    if (value instanceof Float) {
      return pigeonFloatHashCode((float) value);
    }
    return value.hashCode();
  }


  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /**
   * 確認画面が表示する入力内容。
   *
   * 項目ごとにメソッドを分けず**まとめて返す**（手順6.1節）。項目が増えるたびに
   * ネイティブ側の変更が必要になるのを避けるため。
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class FormDataDto {
    private @NonNull String name;

    public @NonNull String getName() {
      return name;
    }

    public void setName(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"name\" is null.");
      }
      this.name = setterArg;
    }

    private @NonNull String email;

    public @NonNull String getEmail() {
      return email;
    }

    public void setEmail(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"email\" is null.");
      }
      this.email = setterArg;
    }

    private @NonNull String message;

    public @NonNull String getMessage() {
      return message;
    }

    public void setMessage(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"message\" is null.");
      }
      this.message = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    FormDataDto() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      FormDataDto that = (FormDataDto) o;
      return pigeonDeepEquals(name, that.name) && pigeonDeepEquals(email, that.email) && pigeonDeepEquals(message, that.message);
    }

    @Override
    public int hashCode() {
      Object[] fields = new Object[] {getClass(), name, email, message};
      return pigeonDeepHashCode(fields);
    }

    @Override
    public String toString() {
      return "FormDataDto{" + "name=" + name + ", " + "email=" + email + ", " + "message=" + message + "}";
    }

    public static final class Builder {

      private @Nullable String name;

      @CanIgnoreReturnValue
      public @NonNull Builder setName(@NonNull String setterArg) {
        this.name = setterArg;
        return this;
      }

      private @Nullable String email;

      @CanIgnoreReturnValue
      public @NonNull Builder setEmail(@NonNull String setterArg) {
        this.email = setterArg;
        return this;
      }

      private @Nullable String message;

      @CanIgnoreReturnValue
      public @NonNull Builder setMessage(@NonNull String setterArg) {
        this.message = setterArg;
        return this;
      }

      public @NonNull FormDataDto build() {
        FormDataDto pigeonReturn = new FormDataDto();
        pigeonReturn.setName(name);
        pigeonReturn.setEmail(email);
        pigeonReturn.setMessage(message);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(name);
      toListResult.add(email);
      toListResult.add(message);
      return toListResult;
    }

    static @NonNull FormDataDto fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      FormDataDto pigeonResult = new FormDataDto();
      Object name = pigeonVar_list.get(0);
      pigeonResult.setName((String) name);
      Object email = pigeonVar_list.get(1);
      pigeonResult.setEmail((String) email);
      Object message = pigeonVar_list.get(2);
      pigeonResult.setMessage((String) message);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return FormDataDto.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof FormDataDto) {
        stream.write(129);
        writeValue(stream, ((FormDataDto) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }

  /**
   * 移行前のネイティブコードが保持しているデータを読む。
   *
   * このデータの所有者はネイティブのままで、Flutterからは読むだけ
   * （手順6.2節）。移行が完了した時点でこのAPIごと消える。
   *
   * Generated interface from Pigeon that represents a handler of messages from Flutter.
   */
  public interface LegacyStoreApi {

    @NonNull 
    FormDataDto readFormData();

    /** The codec used by LegacyStoreApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `LegacyStoreApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable LegacyStoreApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable LegacyStoreApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.legacyapp_flutter.LegacyStoreApi.readFormData" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                try {
                  FormDataDto output = api.readFormData();
                  wrapped.add(0, output);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
